### ISSUE TITLE
Failing KEVM specs

### ISSUE THREAD

**Issue by ttuegel** [runtimeverification/haskell-backend#2113]
In order to deprecate the Java backend, the Haskell backend must pass the specs from [KEVM](https://github.com/kframework/evm-semantics). We will track the list of failing specs here. When the tests pass, and are not too slow, they should be enabled in the evm-semantics repository.

- [ ] tests/specs/benchmarks/bytes00-spec.k (very slow)
- [ ] tests/specs/benchmarks/ecrecover00-siginvalid-spec.k (timeout)
- [ ] tests/specs/benchmarks/ecrecover00-sigvalid-spec.k (timeout)
- [ ] tests/specs/benchmarks/ecrecoverloop00-sig0-invalid-spec.k (timeout)
- [ ] tests/specs/benchmarks/ecrecoverloop00-sig1-invalid-spec.k (timeout)
- [ ] tests/specs/benchmarks/ecrecoverloop00-sigs-valid-spec.k (timeout)
- [ ] tests/specs/benchmarks/ecrecoverloop02-sig0-invalid-spec.k (timeout)
- [ ] tests/specs/benchmarks/ecrecoverloop02-sig1-invalid-spec.k (timeout)
- [ ] tests/specs/benchmarks/ecrecoverloop02-sigs-valid-spec.k (timeout)
- [ ] tests/specs/benchmarks/encode-keccak00-spec.k (timeout in frontend)
- [ ] tests/specs/benchmarks/encodepacked-keccak01-spec.k (missing simplification rule?)
- [ ] tests/specs/benchmarks/keccak00-spec.k (timeout)
- [x] tests/specs/benchmarks/staticarray00-spec.k
- [x] tests/specs/benchmarks/storagevar02-nooverflow-spec.k
- [ ] tests/specs/bihu/collectToken-spec.k (timeout)
- [ ] tests/specs/bihu/forwardToHotWallet-failure-1-spec.k (timeout)
- [ ] tests/specs/bihu/forwardToHotWallet-failure-2-spec.k (timeout)
- [ ] tests/specs/bihu/forwardToHotWallet-failure-3-spec.k (timeout)
- [ ] tests/specs/bihu/forwardToHotWallet-failure-4-spec.k (timeout)
- [ ] tests/specs/bihu/forwardToHotWallet-success-1-spec.k (timeout)
- [ ] tests/specs/bihu/forwardToHotWallet-success-2-spec.k (timeout)
- [ ] tests/specs/erc20/ds/allowance-spec.k (out of gas)
- [ ] tests/specs/erc20/ds/approve-failure-spec.k (out of gas)
- [ ] tests/specs/erc20/ds/approve-success-spec.k (out of gas)
- [ ] tests/specs/erc20/ds/balanceOf-spec.k (out of gas)
- [ ] tests/specs/erc20/ds/totalSupply-spec.k (out of gas)
- [ ] tests/specs/erc20/ds/transfer-failure-1-a-spec.k (out of gas)
- [ ] tests/specs/erc20/ds/transfer-failure-1-b-spec.k (out of gas)
- [ ] tests/specs/erc20/ds/transfer-failure-1-c-spec.k (out of gas)
- [ ] tests/specs/erc20/ds/transfer-failure-2-a-spec.k (out of gas)
- [ ] tests/specs/erc20/ds/transfer-failure-2-b-spec.k (out of gas)
- [ ] tests/specs/erc20/ds/transferFrom-failure-1-a-spec.k (out of gas)
- [ ] tests/specs/erc20/ds/transferFrom-failure-1-b-spec.k (out of gas)
- [ ] tests/specs/erc20/ds/transferFrom-failure-1-c-spec.k (out of gas)
- [ ] tests/specs/erc20/ds/transferFrom-failure-1-d-spec.k (out of gas)
- [ ] tests/specs/erc20/ds/transferFrom-failure-2-a-spec.k (out of gas)
- [ ] tests/specs/erc20/ds/transferFrom-failure-2-b-spec.k (out of gas)
- [ ] tests/specs/erc20/ds/transferFrom-failure-2-c-spec.k (out of gas)
- [ ] tests/specs/erc20/ds/transferFrom-success-1-spec.k (out of gas)
- [ ] tests/specs/erc20/ds/transferFrom-success-2-spec.k (out of gas)
- [ ] tests/specs/erc20/ds/transfer-success-1-spec.k (out of gas)
- [ ] tests/specs/erc20/ds/transfer-success-2-spec.k (out of gas)
- [ ] tests/specs/erc20/hkg/allowance-spec.k (out of gas)
- [ ] tests/specs/erc20/hkg/approve-spec.k (out of gas)
- [ ] tests/specs/erc20/hkg/balanceOf-spec.k (out of gas)
- [ ] tests/specs/erc20/hkg/transfer-failure-1-spec.k (out of gas)
- [ ] tests/specs/erc20/hkg/transfer-failure-2-spec.k (out of gas)
- [ ] tests/specs/erc20/hkg/transferFrom-failure-1-spec.k (out of gas)
- [ ] tests/specs/erc20/hkg/transferFrom-failure-2-spec.k (out of gas)
- [ ] tests/specs/erc20/hkg/transferFrom-success-1-spec.k (out of gas)
- [ ] tests/specs/erc20/hkg/transferFrom-success-2-spec.k (out of gas)
- [ ] tests/specs/erc20/hkg/transfer-success-1-spec.k (out of gas)
- [ ] tests/specs/erc20/hkg/transfer-success-2-spec.k (out of gas)
- [ ] ~tests/specs/imp-specs/imp-specs-test-spec.k~ (build system problem)
- [ ] tests/specs/mcd/cat-exhaustiveness-spec.k (timeout) (#2118)
- [ ] tests/specs/mcd/cat-file-addr-pass-rough-spec.k (timeout) (#2118)
- [ ] tests/specs/mcd/cat-ilks-pass-spec.k (timeout) (#2118)
- [x] tests/specs/mcd/dai-adduu-fail-rough-spec.k
- [ ] tests/specs/mcd/dai-symbol-pass-spec.k (timeout) (#2118)
- [ ] tests/specs/mcd/dstoken-approve-fail-rough-spec.k (timeout) (#2118)
- [ ] tests/specs/mcd/dstoken-transferfrom-fail-rough-spec.k (timeout) (#2118)
- [ ] tests/specs/mcd/dsvalue-read-pass-spec.k (timeout) (#2118)
- [ ] tests/specs/mcd/end-subuu-pass-spec.k (timeout) (#2118)
- [ ] tests/specs/mcd/flipper-tau-pass-spec.k (timeout) (#2118)
- [ ] tests/specs/mcd/vat-deny-diff-fail-rough-spec.k (timeout) (#2118)
- [ ] tests/specs/mcd/vat-move-diff-spec.k (timeout) (#2118)
- [ ] tests/specs/opcodes/create-spec.k (internal error, probably related to undefined functions `#memWidth`, `#memStart`)

**Comment by ehildenb** [comment]
`out of gas` failures will be likely because it cannot prune a path that it needs to prune, so the side condition needs to be inspected when it takes the branch which leads to out of gas, and we need to figure out the correct KEVM rule to add which prunes that branch.

**Comment by ttuegel** [comment]
Action items from our first KEVM + Haskell backend meeting:

- [ ] The `tests/specs/erc20` specs use the Java backend's `#gas(_, _, _)` abstraction. These should be ported to use the infinite `#gas(_)` abstraction used in the `tests/specs/benchmarks` specs. Both abstractions should be factored out into a common file.
- [ ] The `_++_` symbol defined in `evm-types.md` can be a macro.
- [ ] We should try making `#encodeArgs` a concrete function, and add high-level symbolic reasoning lemmas about it as needed. This will be faster, and failures will be easier to understand.

**Comment by ttuegel** [comment]
Making `_++_` into a macro doesn't help because of #1978. I also noticed that this function is marked for the SMT solver, and making it a macro will defeat that.

**Comment by ttuegel** [comment]
All the `mcd` specs will probably need #2118.

**Comment by ttuegel** [comment]
After kframework/evm-semantics#915, the ERC20 specs will need #1978.

**Comment by ttuegel** [comment]
We are going to put off working on the `mcd` specs now, because they are still in-progress. The `erc20` specs all need #1978.
