### ISSUE TITLE
EVM semantics

### ISSUE THREAD

**Issue by ttuegel** [runtimeverification/haskell-backend#2214]
### Integration

- [x] #2207: Solver reset interval should be configurable
- [x] #2208: Retry failed SMT queries once
- [x] #2226: Rule merger breaks on KEVM (in progress)

### Correctness

- [x] #1916: #Ceil rule depending on top constraint not applied
- [x] #1944: Simplify double negation
- [x] #1962: Polymorphic symbols not sent to solver
- [x] #1990: Make #Ceil failure obvious in configuration
- [x] #1993: Symbolic rules for SET.difference
- [x] #2014: Symbolic rules for ==String
- [x] #2019: Symbolic rules for ==Int
- [x] #2020: SymbolicRules for SET.in
- [ ] #2032: Cannot simplify proof dealing with indirect equalities
- [x] #2061: ERC20 stuck with `#Not ( #Ceil ( _ ) )`
- [x] #2076: Unsimplified function in proof (regression)
- [ ] #2113: Failing KEVM specs
- [ ] #2131: Debug failing MCD specs
- [ ] #2227: Cannot evaluate simple predicate without SMT solver

### Performance

- [ ] #1925: KEVM performance
- [ ] #2101: Very slow KEVM proof
- [ ] #2120: Inefficient Equation renaming
- [ ] #2196: Concrete function definitions (in progress)
- [ ] #2229: Performance regression
