### ISSUE TITLE
C semantics

### ISSUE THREAD

**Issue by ttuegel** [runtimeverification/haskell-backend#2215]
- [x] runtimeverification/c-semantics#196: Validate the execution semantics with Haskell backend
- [ ] runtimeverification/c-semantics#197: Validate the linked program with Haskell backend (in progress)
- [ ] runtimeverification/c-semantics#198: Symbolic FFI
- [ ] runtimeverification/c-semantics#199: Run concrete tests with Haskell backend
   Due: 30 Nov 2020.

- [x] #2124: Update parser for \left-assoc and \right-assoc
- [x] #2242: kore-parser: Do not show Haskell data type
- [x] #2256: Change concrete syntax of Bytes
- [ ] #2012: Map and Set keys with uninterpreted functions
- [ ] #2189: Improve the performance of the Kore parser
