### ISSUE TITLE
Michelson semantics

### ISSUE THREAD

**Issue by ttuegel** [runtimeverification/haskell-backend#2216]
### Bugs

- [x] #2221: Claim with `ensures` causes normalization error
- [x] #2244: Error in SideCondition normalization
- [x] #2010: Unable to narrow on results of uninterpreted functions
- [x] #2023: Rewriting multiple items in a KSequence
- [x] #2089: Unsatisfiable branch not pruned
- [x] #2109: `==Int` not correctly simplified
- [ ] #2247: MAP.lookup with symbolic key
- [ ] #2248: MAP.update with symbolic key

### Integration

- [x] #2204: kore-exec: `--strategy all`
- [x] #2205: `--strategy all` is ignored (in progress)
