### ISSUE TITLE
IELE semantics

### ISSUE THREAD

**Issue by ttuegel** [runtimeverification/haskell-backend#2218]
- [x] runtimeverification/iele-semantics#177: Build IELE on Haskell backend
- [x] runtimeverification/iele-semantics#184: Triage test failures on Haskell backend
- [x] runtimeverification/iele-semantics#179: Pass tests on Haskell backend
   Due: 11 Dec 2020

- [x] #2251: STRING.string2base doesn't handle negative hex values
- [x] #2253: Missing hook: LIST.make
