### ISSUE TITLE
Usability for KEVM

### ISSUE THREAD

**Issue by JKTKops** [runtimeverification/haskell-backend#2691]
Everett suggested I keep an issue here to keep track of our ideas for improving usability from the KEVM team. Starting next week, I'll be working more on the Haskell backend directly with the goal to "Make KEVM faster."

So far, our ideas mostly revolve around making it easier to profile proofs.
- [x] #2682, for getting timing data about particular `rule`s from log entries
- [ ] Possible options for `kore-prof` to un-munge label names for readability.
- [x] Potentially, this error should use the frame name instead of number:
```
$ kore-prof tests/specs/benchmarks/bytes00-spec.k.eventlog
kore-prof: expected FrameId {unFrameId = 584} but found FrameId {unFrameId = 579}
CallStack (from HasCallStack):
  error, called at src/Speedscope/Main.hs:460:12 in eventlog2speedscope-0.1.0IC2BnPwv5k795iKdGZButL:Speedscope.Main
  popThread, called at src/Speedscope/Main.hs:472:3 in eventlog2speedscope-0.1.0IC2BnPwv5k795iKdGZButL:Speedscope.Main
```
- [x] A way to ask for the state to be output at various depths, but without terminating the proof, e.g. "output the claim state at depths 10, 25, 50, and 100." Bonus points if each depth can be output to a different file.
- [ ] Is some kind of tail recursion optimization possible for function symbols? We have a particular function that takes 6-10s to simplify and we think this might be an avenue to speed it up.
- [x] Some way to output the number of steps used by the proof. Attaching this information to `DebugProven` would be sufficient.
  (edit: this may already exist in `InfoProofDepth`)

- [x] Document exactly when log entries are emitted along with the log entries. Possible with a longer help text, or with a specific help text for each entry that you have to ask for (not output normally with `--help`.
- [ ] It would be nice if we had a way to separate the timing data of simplifying arguments, unification, and side condition simplification in log entries. In other words, we think we could use `DebugSimplifyArguments`, `DebugUnification`, and `DebugSimplifySideCondition` entries. As-is, we can roughly attribute time to rule transitions and to (attempted) equation applications. We might also be misunderstanding the simplification process, in which case please let us know. This information isn't available in speedscope logs either.
- [ ] Output enough information to figure out which node a log entry (in general) or at least `DebugTransition` and `DebugAttemptEquation` (in specific) are emitted from. That way we can then pull up that node in the kore-repl and then use standard (not oneline) logs to look at the term the equation is being applied to. Using standard logs on the entire proof is not really an option as it generates far too much output that is also quite a bit harder to process.

**Comment by ana-pantilie** [comment]
Most of these are either done, or WIP. If we find out we need to de-munge labels in kore-prof or we need to implement tail recursion optimisations we can open new issues for them when the time comes.
